name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Cache node_modules
        with:
          path: '**/node_modules'
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}-v2
          restore-keys: |
            ${{runner.os}}-yarn-v2

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Lint Prettier
        run: yarn lint:prettier

      - name: Lint ESLint
        run: yarn lint

      - name: Build Storybook
        run: yarn build-storybook

      - name: Build Next.js
        run: cd website && yarn build
