name: CI

on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 14
        uses: actions/setup-node@master
        with:
          node-version: 14

      - uses: actions/cache@v2
        name: Cache node_modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: Install
        run: yarn

      - name: Type Check
        run: yarn type-check

      - name: Lint Check
        run: yarn lint-check
    
      - name: Build Storybook
        run: yarn build-storybook