name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.0

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Lint Prettier
        run: pnpm lint:prettier

      - name: Lint ESLint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build Storybook
        run: pnpm build-storybook
